"use client";
import {useMemo,useState} from "react";
import Management from "./management";
import {LayoutDashboard,Package,ArrowDownToLine,ArrowUpFromLine,ShoppingCart,Warehouse,Boxes,RotateCcw,BarChart3,Settings,Search,Bell,Plus,AlertTriangle,Moon,Sun} from "lucide-react";

type Product={sku:string;name:string;category:string;stock:number;reserved:number;cost:number;price:number;status:string};
const initial:Product[]=[
{sku:"VON-001",name:"Vondex Classic Watch",category:"Watches",stock:148,reserved:12,cost:310,price:799,status:"Healthy"},
{sku:"NID-BLT-021",name:"Premium Leather Belt",category:"Belts",stock:31,reserved:5,cost:220,price:599,status:"Low Stock"},
{sku:"RR-SOAP-014",name:"RootedRitual Herbal Soap",category:"Personal Care",stock:0,reserved:0,cost:82,price:249,status:"Out of Stock"},
{sku:"VON-017",name:"Vondex Chrono Black",category:"Watches",stock:67,reserved:9,cost:520,price:1299,status:"Healthy"},
{sku:"HM-BAG-008",name:"Luxury Hand Bag",category:"Bags",stock:22,reserved:3,cost:780,price:1899,status:"Healthy"}];
const nav=[["Overview",LayoutDashboard],["Products",Package],["Stock In",ArrowDownToLine],["Stock Out",ArrowUpFromLine],["Purchases",ShoppingCart],["Orders",Boxes],["Warehouses",Warehouse],["Returns",RotateCcw],["Reports",BarChart3],["Settings",Settings]] as const;
const money=(n:number)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(n);

export default function Home(){
 const [active,setActive]=useState("Overview"),[products,setProducts]=useState(initial),[query,setQuery]=useState(""),[dark,setDark]=useState(false);
 const filtered=useMemo(()=>products.filter(p=>(p.name+p.sku+p.category).toLowerCase().includes(query.toLowerCase())),[products,query]);
 const units=products.reduce((s,p)=>s+p.stock,0),value=products.reduce((s,p)=>s+p.stock*p.cost,0),low=products.filter(p=>p.status==="Low Stock").length,out=products.filter(p=>p.status==="Out of Stock").length;
 const stockIn=()=>{const sku=prompt("SKU"),qty=Number(prompt("Quantity","10"));if(!sku||!qty)return;setProducts(ps=>ps.map(p=>p.sku===sku?{...p,stock:p.stock+qty,status:p.stock+qty>20?"Healthy":"Low Stock"}:p))};
 const stockOut=()=>{const sku=prompt("SKU"),qty=Number(prompt("Quantity","1"));if(!sku||!qty)return;setProducts(ps=>ps.map(p=>p.sku===sku?{...p,stock:Math.max(0,p.stock-qty),status:p.stock-qty<=0?"Out of Stock":p.stock-qty<=20?"Low Stock":"Healthy"}:p))};
 return <main className={dark?"app dark":"app"}>
 <aside className="sidebar"><div className="brand"><div className="logo">S</div><div><b>StockOS</b><small>Inventory Suite</small></div></div><div className="workspace">SPACEWAY DIGITAL</div><nav>{nav.map(([label,Icon])=><button className={active===label?"nav active":"nav"} key={label} onClick={()=>setActive(label)}><Icon size={17}/>{label}{label==="Orders"&&<em>12</em>}</button>)}</nav><div className="system">● All systems operational</div></aside>
 <section className="content"><header><div><h1>{active}</h1><p>26 September 2026 · Live inventory</p></div><div className="head"><div className="search"><Search size={16}/><input placeholder="Search SKU, product..." value={query} onChange={e=>setQuery(e.target.value)}/></div><button className="icon" onClick={()=>setDark(!dark)}>{dark?<Sun size={17}/>:<Moon size={17}/>}</button><button className="icon"><Bell size={17}/></button><div className="avatar">PY</div></div></header>
 {active==="Overview"?<><div className="hero"><div><label>INVENTORY COMMAND CENTER</label><h2>Know your stock. <span>Run your business.</span></h2><p>One central ledger for purchase, stock, sales, warehouse and ecommerce.</p></div><button className="primary" onClick={stockIn}><Plus size={16}/> Receive Stock</button></div>
 <div className="metrics"><Metric t="Inventory Value" v={money(value)} i={BarChart3}/><Metric t="Units in Stock" v={units.toLocaleString("en-IN")} i={Package}/><Metric t="Low Stock" v={String(low)} i={AlertTriangle}/><Metric t="Out of Stock" v={String(out)} i={Boxes}/></div>
 <div className="grid"><div className="card"><h3>Stock overview</h3><p>Current inventory by category</p><div className="bars"><Bar n="Watches" v={215}/><Bar n="Belts" v={31}/><Bar n="Personal Care" v={48}/><Bar n="Bags" v={22}/></div></div><div className="card"><h3>Today's movement</h3><p>Live business activity</p><div className="today"><Stat n="Stock In" v="86 units"/><Stat n="Stock Out" v="132 units"/><Stat n="Purchases" v={money(48650)}/><Stat n="Sales" v={money(104920)}/></div></div></div>
 <div className="card"><div className="row"><div><h3>Inventory</h3><p>Real-time SKU stock ledger</p></div><div><button className="secondary" onClick={stockOut}>Stock Out</button> <button className="primary small" onClick={stockIn}>Stock In</button></div></div><div className="table"><table><thead><tr><th>PRODUCT</th><th>SKU</th><th>CATEGORY</th><th>STOCK</th><th>RESERVED</th><th>AVAILABLE</th><th>VALUE</th><th>STATUS</th></tr></thead><tbody>{filtered.map(p=><tr key={p.sku}><td><b>{p.name}</b></td><td>{p.sku}</td><td>{p.category}</td><td>{p.stock}</td><td>{p.reserved}</td><td>{p.stock-p.reserved}</td><td>{money(p.stock*p.cost)}</td><td><span className={"badge "+p.status.toLowerCase().replaceAll(" ","-")}>{p.status}</span></td></tr>)}</tbody></table></div></div></>:<Management/>}
 <footer>StockOS v1.0 · Central Inventory Engine · API-ready for Amazon, Flipkart, Myntra, Meesho & Shopify</footer></section></main>
}
function Metric({t,v,i:Icon}:{t:string;v:string;i:any}){return <div className="metric"><Icon size={18}/><div><small>{t}</small><strong>{v}</strong></div></div>}
function Bar({n,v}:{n:string;v:number}){return <div className="bar"><div><span>{n}</span><b>{v}</b></div><i style={{width:Math.min(v/2.5,100)+"%"}}/></div>}
function Stat({n,v}:{n:string;v:string}){return <div className="stat"><small>{n}</small><b>{v}</b></div>}
function Module({active,products,onIn,onOut}:{active:string;products:Product[];onIn:()=>void;onOut:()=>void}){const map:Record<string,string>={Products:"Product master — SKUs, variants, barcode, pricing and reorder levels", "Stock In":"Receive purchases, returns and warehouse transfers","Stock Out":"Dispatch sales, ecommerce orders, transfers and adjustments",Purchases:"Purchase orders, GRN, invoices, vendors and payments",Orders:"Central order inbox for ecommerce channels",Warehouses:"Warehouses, zones, racks, shelves, bins and transfers",Returns:"Customer returns, RTO, QC and restocking",Reports:"Inventory valuation, sales, profit, aging and movement",Settings:"Users, roles, tax and integrations"};return <><div className="hero"><div><label>MODULE</label><h2>{active}</h2><p>{map[active]}</p></div><button className="primary" onClick={active==="Stock Out"?onOut:onIn}><Plus size={16}/> Add New</button></div><div className="card"><div className="features">{["Real-time data","Role-based access","Audit trail","Excel export","Barcode ready","API connector ready"].map(x=><div className="feature" key={x}>✓ <b>{x}</b></div>)}</div>{active==="Products"&&<div className="table"><table><thead><tr><th>PRODUCT</th><th>SKU</th><th>STOCK</th><th>COST</th><th>PRICE</th><th>STATUS</th></tr></thead><tbody>{products.map(p=><tr key={p.sku}><td><b>{p.name}</b></td><td>{p.sku}</td><td>{p.stock}</td><td>{money(p.cost)}</td><td>{money(p.price)}</td><td>{p.status}</td></tr>)}</tbody></table></div>}</div></>}
